### PR TITLE
[Tech 9] Navigation Menu UI + Functionality

### PR DESCRIPTION
**Pull request by ThunderRoar**
Changes:
1. Add navigation bar to every page with functionality
2. Responsive on both mobile and desktop view
3. Has slide in animation on mobile view 
4. Dynamic routes on mobile nav based on current page

### CODE REVIEW

**Review by danielalyoshin — CHANGES_REQUESTED** [review]
Three fixes from a design review POV.

1. On mobile when closing the nav during the animation the close button jumps down the nav as its closing. If its a quick fix look into it otherwise leave it be no biggie.

2. I have added a different icon now to sit beside the Log In button rather than this one which is solely for when the user is actually logged in.

3. I am not seeing the proper custom fonts being used. The fonts used in figma are of the "Montserrat" family and are readily available online, I suggest we use [the package offered via Google Fonts](https://fonts.google.com/specimen/Montserrat). 

@murphylee10 How are we planning on hosting these fonts, will they be a local file within the repo or should we pull them from Google Fonts using something like:

```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
```
or

```html
<style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
</style>
```

or 

```css
// <uniquifier>: Use a unique and descriptive class name
// <weight>: Use a value from 100 to 900

.montserrat-<uniquifier> {
  font-family: "Montserrat", sans-serif;
  font-optical-sizing: auto;
  font-weight: <weight>;
  font-style: normal;
}
```

**Comment by danielalyoshin** [comment]
> Three fixes from a design review POV.
> 
> 1. On mobile when closing the nav during the animation the close button jumps down the nav as its closing. If its a quick fix look into it otherwise leave it be no biggie.
> 2. I have added a different icon now to sit beside the Log In button rather than this one which is solely for when the user is actually logged in.
> 3. I am not seeing the proper custom fonts being used. The fonts used in figma are of the "Montserrat" family and are readily available online, I suggest we use [the package offered via Google Fonts](https://fonts.google.com/specimen/Montserrat).
> 
> @murphylee10 How are we planning on hosting these fonts, will they be a local file within the repo or should we pull them from Google Fonts using something like:
> 
> ```
> <link rel="preconnect" href="https://fonts.googleapis.com">
> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
> <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
> ```
> 
> or
> 
> ```
> <style>
> @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
> </style>
> ```
> 
> and
> 
> ```css
> // <uniquifier>: Use a unique and descriptive class name
> // <weight>: Use a value from 100 to 900
> 
> .montserrat-<uniquifier> {
>   font-family: "Montserrat", sans-serif;
>   font-optical-sizing: auto;
>   font-weight: <weight>;
>   font-style: normal;
> }
> ```

@ThunderRoar I have added the fonts, please merge dev into this branch to access. [PR for reference](https://github.com/amacss-utsc/amacss_site_v2/pull/8).

**Comment by ThunderRoar** [comment]
The icon for login status is now also dynamic based on user's activity and CLOSE button for the mobile was a quick fix. The fonts were not appearing as they were not imported even though it was applied to the navigation bar which is fixed now at the root level.

**Review by danielalyoshin — APPROVED** [review]
Looking good!

**Pull request merged**
